import './globals.css'
import Nav from './components/Nav'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { bitter } from './fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={`${bitter.className} antialiased bg-[#F7F2EE]`}>
        <Nav user={session?.user} expires={session?.expires as string} />
        {children}
      </body>
    </html>
  )
}
